### ISSUE TITLE
 java.lang.NoSuchMethodError: org.apache.zookeeper.ZooKeeper.<init>(Ljava/lang/String;ILorg/apache/zookeeper/Watcher;Z)V

### ISSUE THREAD

**Issue by nidonglin** [DDTH/ddth-kafka#1]
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.zookeeper.ZooKeeper.<init>(Ljava/lang/String;ILorg/apache/zookeeper/Watcher;Z)V
    at org.apache.curator.utils.DefaultZookeeperFactory.newZooKeeper(DefaultZookeeperFactory.java:29)
    at org.apache.curator.framework.imps.CuratorFrameworkImpl$2.newZooKeeper(CuratorFrameworkImpl.java:169)
    at org.apache.curator.HandleHolder$1.getZooKeeper(HandleHolder.java:94)
    at org.apache.curator.HandleHolder.getZooKeeper(HandleHolder.java:55)
    at org.apache.curator.ConnectionState.reset(ConnectionState.java:219)
    at org.apache.curator.ConnectionState.start(ConnectionState.java:103)
    at org.apache.curator.CuratorZookeeperClient.start(CuratorZookeeperClient.java:188)
    at org.apache.curator.framework.imps.CuratorFrameworkImpl.start(CuratorFrameworkImpl.java:234)
    at com.github.ddth.zookeeper.ZooKeeperClient._connect(ZooKeeperClient.java:534)
    at com.github.ddth.zookeeper.ZooKeeperClient.init(ZooKeeperClient.java:656)
    at com.github.ddth.kafka.KafkaClient.init(KafkaClient.java:117)
    at org.apache.myfaces.blank.ConsumerDemo5.main(ConsumerDemo5.java:20)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

**Comment by btnguyen2k** [comment]
Hi nidonglin, for some reasons maven pull an old version of Apache Zookeeper which does not have this method. I'm checking on this issue.
A workaround for now is to add Apache Zookeeper 3.4.6+ explicitly to your project.

**Comment by sumanreddyk** [comment]
Hi, I am using kafka_2.12-2.2.0 in Mac OS. zookeeper server is up and running fine, but, kafka server is throwing the below exception.
Could you please suggest me on this issue.

2019-03-27T20:36:43,378 INFO [LogDirFailureHandler] kafka.server.ReplicaManager$LogDirFailureHandler - [LogDirFailureHandler]: Starting
2019-03-27T20:36:43,456 INFO [main] kafka.zk.KafkaZkClient - Creating /brokers/ids/0 (is it secure? false)
2019-03-27T20:36:43,488 ERROR [main] kafka.server.KafkaServer - [KafkaServer id=0] Fatal error during KafkaServer startup. Prepare to shutdown
java.lang.NoSuchMethodError: org.apache.zookeeper.ZooKeeper.multi(Ljava/lang/Iterable;Lorg/apache/zookeeper/AsyncCallback$MultiCallback;Ljava/lang/Object;)V
        at kafka.zookeeper.ZooKeeperClient.send(ZooKeeperClient.scala:222) ~[kafka_2.12-2.2.0.jar:?]
        at kafka.zookeeper.ZooKeeperClient.$anonfun$handleRequests$2(ZooKeeperClient.scala:144) ~[kafka_2.12-2.2.0.jar:?]
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23) ~[scala-library-2.12.8.jar:?]
        at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:251) ~[kafka_2.12-2.2.0.jar:?]
        at kafka.utils.CoreUtils$.inReadLock(CoreUtils.scala:257) ~[kafka_2.12-2.2.0.jar:?]
        at kafka.zookeeper.ZooKeeperClient.$anonfun$handleRequests$1(ZooKeeperClient.scala:144) ~[kafka_2.12-2.2.0.jar:?]
        at kafka.zookeeper.ZooKeeperClient.$anonfun$handleRequests$1$adapted(ZooKeeperClient.scala:140) ~[kafka_2.12-2.2.0.jar:?]
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62) ~[scala-library-2.12.8.jar:?]
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55) ~[scala-library-2.12.8.jar:?]
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49) ~[scala-library-2.12.8.jar:?]
        at kafka.zookeeper.ZooKeeperClient.handleRequests(ZooKeeperClient.scala:140) ~[kafka_2.12-2.2.0.jar:?]
        at kafka.zk.KafkaZkClient.retryRequestsUntilConnected(KafkaZkClient.scala:1660) ~[kafka_2.12-2.2.0.jar:?]
        at kafka.zk.KafkaZkClient.retryRequestsUntilConnected(KafkaZkClient.scala:1647) ~[kafka_2.12-2.2.0.jar:?]
        at kafka.zk.KafkaZkClient.retryRequestUntilConnected(KafkaZkClient.scala:1642) ~[kafka_2.12-2.2.0.jar:?]
        at kafka.zk.KafkaZkClient$CheckedEphemeral.create(KafkaZkClient.scala:1712) ~[kafka_2.12-2.2.0.jar:?]
        at kafka.zk.KafkaZkClient.checkedEphemeralCreate(KafkaZkClient.scala:1689) ~[kafka_2.12-2.2.0.jar:?]
        at kafka.zk.KafkaZkClient.registerBroker(KafkaZkClient.scala:97) ~[kafka_2.12-2.2.0.jar:?]
        at kafka.server.KafkaServer.startup(KafkaServer.scala:260) [kafka_2.12-2.2.0.jar:?]
        at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38) [kafka_2.12-2.2.0.jar:?]
        at kafka.Kafka$.main(Kafka.scala:75) [kafka_2.12-2.2.0.jar:?]
        at kafka.Kafka.main(Kafka.scala) [kafka_2.12-2.2.0.jar:?]
2019-03-27T20:36:43,494 INFO [main] kafka.server.KafkaServer - [KafkaServer id=0] shutting down
2019-03-27T20:36:43,501 INFO [main] kafka.network.SocketServer - [SocketServer brokerId=0] Stopping socket server request processors

**Comment by ChenJhua** [comment]
Hello, I also encountered the problem, how do you solve it？

**Comment by sumanreddyk** [comment]
@ChenJhua , I have fixed this issue.
I had downloaded kafka 2.0.0 version instead 2.2.0. 
Kafka 2.0.0 is running perfectly fine without any trouble.

**Comment by ssomani7** [comment]
@sumanreddyk thank you for providing this quick fix. I ran into the same problem and now my kafka server is working fine after down grading to kafka 2.0.0
